In [1]:
from tensorflow.keras.preprocessing.text import one_hot

# sentences

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

# Vocabulary size

In [3]:
### Vocabulary size
voc_size=10000

# Applying OneHot Encoding 

In [4]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[7700, 6964, 7050, 2619], [7700, 6964, 7050, 7861], [7700, 3597, 7050, 1828], [5295, 3727, 4348, 9254, 4854], [5295, 3727, 4348, 9254, 8929], [1038, 7700, 4632, 7050, 8602], [6100, 8210, 5972, 9254]]


# Creating Model 

In [5]:
 from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

## Applying Padding 

In [7]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7700 6964 7050 2619]
 [   0    0    0    0 7700 6964 7050 7861]
 [   0    0    0    0 7700 3597 7050 1828]
 [   0    0    0 5295 3727 4348 9254 4854]
 [   0    0    0 5295 3727 4348 9254 8929]
 [   0    0    0 1038 7700 4632 7050 8602]
 [   0    0    0    0 6100 8210 5972 9254]]


## Building Model 

In [8]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))   # 10 is dimention each one hot converted word be embedded to 10 dimentional vector
model.compile('adam','mse')

D:\conda\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [9]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

# Embedding 1St Sentence 

In [11]:
print(model.predict(embedded_docs)[0])  # each word after applyting OME is embedded to 10 dimentional vector 

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[[ 0.01368009  0.04558991  0.01132729  0.03401026 -0.0379302   0.04283759
  -0.0436375   0.04600289  0.02059649  0.04407569]
 [ 0.01368009  0.04558991  0.01132729  0.03401026 -0.0379302   0.04283759
  -0.0436375   0.04600289  0.02059649  0.04407569]
 [ 0.01368009  0.04558991  0.01132729  0.03401026 -0.0379302   0.04283759
  -0.0436375   0.04600289  0.02059649  0.04407569]
 [ 0.01368009  0.04558991  0.01132729  0.03401026 -0.0379302   0.04283759
  -0.0436375   0.04600289  0.02059649  0.04407569]
 [-0.01381979 -0.03503861  0.0244554   0.04938294 -0.03431021  0.00668774
  -0.02301731  0.04992063 -0.04847167 -0.0151853 ]
 [-0.03741808  0.04190708 -0.00201254  0.03241557 -0.04953895  0.02999531
  -0.00629296 -0.03573124  0.04666363  0.01598519]
 [ 0.04297629 -0.01647832 -0.01587936  0.03331722 -0.00305869  0.03259932
  -0.02634745  0.03990933  0.03546704 -0.02927399]
 [ 0.00986804  0.03330499 -0.04853634  0.04749559  0.01377055  0.03587241
  -0.0114462 